instructions = """
command to compile "make influence"
"""

[[Taikun Zhang]]
name = "Taikun Zhang"
utor = "zhan4776"
nmbr = "1004050643"

[[student]]
name = "Maytham Mahroos"
utor = "mahroos2"
nmbr = "1002900480"